import {
  addComponent,
  addEntity,
  createIdFactory,
  createRandom,
  createScene,
  type SceneDocument,
} from '@imagi3/core';

/**
 * The reference scene the play-mode frame budget is stated against.
 *
 * **Generated by committed code, never shipped as an asset.** The brief forbids
 * third-party asset packs in the repository, and a generated scene is stronger
 * than a licence-clean one anyway: it is regenerable, it is diffable as the
 * function that produced it, and its size is a parameter rather than a file
 * somebody has to re-export.
 *
 * The entity count is the point of the scene. A budget measured against a scene
 * with ten objects measures the browser; one measured against a scene with a
 * realistic count measures the engine. This is what a modest 2D scene looks
 * like — a few hundred moving sprites — and it is deliberately not the largest
 * scene the engine should survive, which is a separate soak measurement.
 */

/** Entities in the reference 2D scene. */
export const REFERENCE_2D_ENTITY_COUNT = 400;

/** Fixed, so the scene is identical on every run and every device. */
export const REFERENCE_2D_SEED = 0x1a61f3;

/**
 * Offsets the id generator from the scene generator.
 *
 * Both are seeded from {@link REFERENCE_2D_SEED}; without an offset they would
 * be the same sequence, and every entity's id would then be a function of its
 * position. Harmless here, and exactly the kind of accidental coupling that is
 * impossible to find later.
 */
const ID_SEED_OFFSET = 0x5bf03635;

const SPREAD = 180;
const SPEED = 40;
const HALF = 0.5;

/**
 * Build the reference scene.
 *
 * Uses the incremental `addEntity` deliberately rather than the bulk path: this
 * is what the editor does, and it is worth having one committed caller that
 * would notice if RC-0008 ever became slow enough to matter at this size.
 */
export function createReferenceScene(entityCount = REFERENCE_2D_ENTITY_COUNT): SceneDocument {
  const random = createRandom(REFERENCE_2D_SEED);
  const ids = createIdFactory(createRandom(REFERENCE_2D_SEED ^ ID_SEED_OFFSET));
  let document = createScene(ids, 'reference 2d');

  for (let i = 0; i < entityCount; i += 1) {
    const added = addEntity(document, ids, { name: `sprite ${String(i)}` });
    document = addComponent(added.document, ids, added.id, 'transform', {
      x: (random.next() - HALF) * SPREAD,
      y: (random.next() - HALF) * SPREAD,
    }).document;
    document = addComponent(document, ids, added.id, 'motion', {
      vx: (random.next() - HALF) * SPEED,
      vy: (random.next() - HALF) * SPEED,
      controlled: false,
    }).document;
  }
  return document;
}
